obj-$(CONFIG_LIXUN_ADAPTER_CLASS)	+= lx_adapter_class.o

obj-$(CONFIG_LIXUN_CHARGER_CLASS)	+= lx_charger_class.o lx_fg_class.o

obj-$(CONFIG_LIXUN_CP_CLASS)		+= lx_cp_class.o

obj-$(CONFIG_LIXUN_CP_CLASS)		+= lx_led_class.o

obj-$(CONFIG_PD_BATTERY_SECRET)		+=xm_adapter_class.o
