# MTK include path
subdir-ccflags-y += -I$(srctree)/sound/soc/mediatek/audio_dsp
subdir-ccflags-y += -I$(srctree)/sound/soc/mediatek/common
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/audio_ipi/include
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
subdir-ccflags-y += -I$(srctree)/drivers/base

# debugging support (also enables trace_printk)
ccflags-y += -Werror
ccflags-y += $(call cc-option,-Wno-date-time,)
snd-soc-oca72xxx-objs:= ocspa.o ocspa_device.o ocspa_monitor.o ocspa_fw_process.o  ocspa_fw.o
obj-$(CONFIG_SND_SOC_OCA72XXX) += snd-soc-oca72xxx.o
